import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Рубашка свободного покроя',
      slug: 'free-shirt',
      category: 'Рубашки',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Популярная рубашка свободного покроя',
      isFeatured: true,
      banner: '/images/banner1.jpg',
    },
    {
      name: 'Облегающая рубашка',
      slug: 'fit-shirt',
      category: 'Рубашки',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Популярная рубашка облегающего покроя',
      isFeatured: true,
      banner: '/images/banner2.jpg',
    },
    {
      name: 'Приталенная рубашка',
      slug: 'slim-shirt',
      category: 'Рубашки',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Популярная приталенная рубашка ',
    },
    {
      name: 'Брюки для гольфа',
      slug: 'golf-pants',
      category: 'Брюки',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Шикарно выглядящие брюки',
    },
    {
      name: 'Облегающие брюки',
      slug: 'fit-pants',
      category: 'Брюки',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'Популярные брюки облегающего покроя',
    },
    {
      name: 'Классические брюки',
      slug: 'classic-pants',
      category: 'Брюки',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Популярные брюки классического покроя',
    },
  ],
};

export default data;
